coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: 70%
ignore:
  - "hack/**"
  - "pkg/apis/generated/**"
  - "**/zz_generated.*.go"
  - "pkg/generated/clientset/versioned/clientset.go"
  - "pkg/generated/clientset/versioned/scheme/register.go"
  - "pkg/generated/clientset/versioned/typed/cluster/v1alpha1/cluster_client.go"
  - "pkg/generated/clientset/versioned/typed/cluster/v1alpha1/clustergateway.go"
  - "pkg/generated/clientset/versioned/typed/cluster/v1alpha1/generated_expansion.go"
