apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:cluster-gateway:managedcluster-reader
rules:
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - clustermanagementaddons
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - clustermanagementaddons/finalizers
    verbs:
      - update
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - managedclusteraddons
    verbs:
      - "*"
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - managedclusteraddons/status
    verbs:
      - update
      - patch
  - apiGroups:
      - addon.open-cluster-management.io
    resources:
      - managedclusteraddons/finalizers
    verbs:
      - update
  - apiGroups:
      - authentication.open-cluster-management.io
    resources:
      - managedserviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - proxy.open-cluster-management.io
    resources:
      - clustergatewayconfigurations
      - managedproxyconfigurations/finalizers # need this when copying secret from cluster-proxy.
    verbs:
      - "*"
  - apiGroups:
      - cluster.core.oam.dev
    resources:
      - clustergateways/health
      - clustergateways/proxy
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
      - secrets
      - configmaps
      - events
      - serviceaccounts
      - services
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - work.open-cluster-management.io
    resources:
      - manifestworks
    verbs:
      - "*"
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - prioritylevelconfigurations
      - flowschemas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - bind
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
    verbs:
      - "*"
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - "*"