//go:build !ignore_autogenerated

/*
Copyright 2021 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGatewayConfiguration) DeepCopyInto(out *ClusterGatewayConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGatewayConfiguration.
func (in *ClusterGatewayConfiguration) DeepCopy() *ClusterGatewayConfiguration {
	if in == nil {
		return nil
	}
	out := new(ClusterGatewayConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGatewayConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGatewayConfigurationList) DeepCopyInto(out *ClusterGatewayConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterGatewayConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGatewayConfigurationList.
func (in *ClusterGatewayConfigurationList) DeepCopy() *ClusterGatewayConfigurationList {
	if in == nil {
		return nil
	}
	out := new(ClusterGatewayConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGatewayConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGatewayConfigurationSpec) DeepCopyInto(out *ClusterGatewayConfigurationSpec) {
	*out = *in
	in.SecretManagement.DeepCopyInto(&out.SecretManagement)
	in.Egress.DeepCopyInto(&out.Egress)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGatewayConfigurationSpec.
func (in *ClusterGatewayConfigurationSpec) DeepCopy() *ClusterGatewayConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterGatewayConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGatewayConfigurationStatus) DeepCopyInto(out *ClusterGatewayConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGatewayConfigurationStatus.
func (in *ClusterGatewayConfigurationStatus) DeepCopy() *ClusterGatewayConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterGatewayConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGatewaySecretManagement) DeepCopyInto(out *ClusterGatewaySecretManagement) {
	*out = *in
	if in.ManagedServiceAccount != nil {
		in, out := &in.ManagedServiceAccount, &out.ManagedServiceAccount
		*out = new(SecretManagementManagedServiceAccount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGatewaySecretManagement.
func (in *ClusterGatewaySecretManagement) DeepCopy() *ClusterGatewaySecretManagement {
	if in == nil {
		return nil
	}
	out := new(ClusterGatewaySecretManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGatewayTrafficEgress) DeepCopyInto(out *ClusterGatewayTrafficEgress) {
	*out = *in
	if in.ClusterProxy != nil {
		in, out := &in.ClusterProxy, &out.ClusterProxy
		*out = new(ClusterGatewayTrafficEgressClusterProxy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGatewayTrafficEgress.
func (in *ClusterGatewayTrafficEgress) DeepCopy() *ClusterGatewayTrafficEgress {
	if in == nil {
		return nil
	}
	out := new(ClusterGatewayTrafficEgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGatewayTrafficEgressClusterProxy) DeepCopyInto(out *ClusterGatewayTrafficEgressClusterProxy) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGatewayTrafficEgressClusterProxy.
func (in *ClusterGatewayTrafficEgressClusterProxy) DeepCopy() *ClusterGatewayTrafficEgressClusterProxy {
	if in == nil {
		return nil
	}
	out := new(ClusterGatewayTrafficEgressClusterProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGatewayTrafficEgressClusterProxyCredential) DeepCopyInto(out *ClusterGatewayTrafficEgressClusterProxyCredential) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGatewayTrafficEgressClusterProxyCredential.
func (in *ClusterGatewayTrafficEgressClusterProxyCredential) DeepCopy() *ClusterGatewayTrafficEgressClusterProxyCredential {
	if in == nil {
		return nil
	}
	out := new(ClusterGatewayTrafficEgressClusterProxyCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretManagementManagedServiceAccount) DeepCopyInto(out *SecretManagementManagedServiceAccount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretManagementManagedServiceAccount.
func (in *SecretManagementManagedServiceAccount) DeepCopy() *SecretManagementManagedServiceAccount {
	if in == nil {
		return nil
	}
	out := new(SecretManagementManagedServiceAccount)
	in.DeepCopyInto(out)
	return out
}
